#["database"]
#user="postgres"
#host="db.srgojfkwksdgtxtbabck.supabase.co"
#port=5432
#database="postgres"
#password= "#Ffmbbmho1234$"

[supabase]
url = "https://srgojfkwksdgtxtbabck.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyZ29qZmt3a3NkZ3R4dGJhYmNrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDM1NTQ3NSwiZXhwIjoyMDU5OTMxNDc1fQ.bt9uxyp3q1u-dcZWDzrjN4pdCDwbcuURvwIu2jNP3Is"
